# Generated by Django 5.0.7 on 2024-07-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlist_person_comments_bids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='product',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='product',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='person',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='person',
        ),
        migrations.DeleteModel(
            name='AuctionList',
        ),
        migrations.DeleteModel(
            name='Bids',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
