# Generated by Django 5.0.7 on 2024-07-30 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionlist_bid_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='product',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='person',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='person',
        ),
        migrations.DeleteModel(
            name='AuctionList',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
