# Generated by Django 5.0.7 on 2024-07-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auctionlist_bid_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='image',
            field=models.IntegerField(),
        ),
    ]
