# Generated by Django 5.0.7 on 2024-07-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_auctionlist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
