# Generated by Django 5.0.7 on 2024-08-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_remove_comment_person_remove_comment_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlist',
            name='comment',
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='watchList',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='link',
            name='comment',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
