# Generated by Django 5.0.7 on 2024-08-19 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_remove_auctionlist_comment_auctionlist_watchlist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlist',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='auctionlist',
            name='watchList',
        ),
        migrations.RemoveField(
            model_name='link',
            name='comment',
        ),
        migrations.AddField(
            model_name='link',
            name='bid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='link',
            name='watchList',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_link', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='link',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_link', to='auctions.auctionlist'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000, null=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_comment', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_comment', to='auctions.auctionlist')),
            ],
        ),
    ]
